using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Euler
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 
    ///                                                    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// 
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    class Problem2 : IEulerProblem
    {
        public long solve()
        {
            return evenFib(4000000);
        }

        public int getID()
        {
            return 2;
        }

        private int evenFib(int max)
        {
            int sum = 2;
            int first = 1;
            int second = 2;
            int current = first + second;
            while (current < max)
            {
                if (current % 2 == 0)
                {
                    sum += current;
                }
                first = second;
                second = current;
                current = first + second;
            }
            return sum;
        }
    }
}
